# Generated by Django 3.2.25 on 2025-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_xsrconfiguration_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsrconfiguration',
            name='courses_url',
            field=models.CharField(default='test.com', help_text='Enter the URL to retrieve Coursera courses', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='token_url',
            field=models.CharField(default='test.com', help_text='Enter the token URL for Coursera', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='xsr_api_org_id',
            field=models.CharField(default='123', help_text='Enter the Coursera Organization ID', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='xsr_api_pk',
            field=models.CharField(default='123', help_text='Enter the Coursera Primary Key', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='xsr_api_sk',
            field=models.CharField(default='123', help_text='Enter the Coursera Secret Key', max_length=200),
            preserve_default=False,
        ),
    ]
