# Generated by Django 3.2.25 on 2025-06-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openlxp_xia', '0009_auto_20250225_1536'),
        ('core', '0003_alter_xsrconfiguration_source_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this configuration is active.')),
                ('xia_configuration', models.ForeignKey(blank=True, help_text='Reference to the XIA Configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xia_configuration', to='openlxp_xia.xiaconfiguration')),
                ('xis_configuration', models.ForeignKey(blank=True, help_text='Reference to the XIS Configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xis_configuration', to='openlxp_xia.xisconfiguration')),
                ('xsr_configuration', models.ForeignKey(blank=True, help_text='Reference to the XSR Configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xsr_configuration', to='core.xsrconfiguration')),
            ],
        ),
    ]
