# Generated by Django 3.2.25 on 2025-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configurationmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xsrconfiguration',
            name='source_file',
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='courses_url',
            field=models.CharField(default='val', help_text='Enter the URL to retrieve Coursera courses', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='token_url',
            field=models.CharField(default='val', help_text='Enter the token URL for Coursera', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='xsr_api_org_id',
            field=models.CharField(default='val', help_text='Enter the Coursera Organization ID', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='xsr_api_pk',
            field=models.CharField(default='val', help_text='Enter the Coursera Primary Key', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='xsr_api_sk',
            field=models.CharField(default='val', help_text='Enter the Coursera Secret Key', max_length=200),
            preserve_default=False,
        ),
    ]
