# Generated by Django 3.2.25 on 2025-03-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250224_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xsrconfiguration',
            name='source_file',
        ),
    ]
