# Generated by Django 3.2.25 on 2025-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250709_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsrconfiguration',
            name='key_fields',
            field=models.TextField(blank=True, default='["Course_ID", "CourseProviderName"]', help_text='Enter list of field names to create metadata key', null=True),
        ),
    ]
