# Generated by Django 3.2.25 on 2025-07-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_xsrconfiguration_key_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsrconfiguration',
            name='data_type',
            field=models.CharField(choices=[('course', 'Course Data'), ('competency', 'Competency Data'), ('learner', 'Learner Data')], default='course', help_text='Select the type of data for this configuration', max_length=20),
        ),
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='key_fields',
            field=models.TextField(blank=True, default='["Course_ID","CourseProviderName"]', help_text='Enter list of field names to create metadata key', null=True),
        ),
    ]
